version: 1
builder:
  configs:
  - documentation_targets: [CLI, ValCommand, FrontEnd, Core, IR, CodeGenLLVM, Utils, TestUtils, ValModule, GenerateValFileTests]

    custom_documentation_parameters: [
    --include-extended-types, --enable-inherited-docs,
    --source-service, github,
    --source-service-base-url, https://github.com/val-lang/val/blob/main,
    --checkout-path, .
    ]
