version: 1
builder:
  configs:
  - platform: linux
    # **Do not change without a global search/replace for this version string.**
    swift_version: '5.10'
    image: registry.gitlab.com/finestructure/spi-images:hylo-5.10-latest
    documentation_targets:
    - CLI
    - CodeGenLLVM
    - Core
    - Driver
    - FrontEnd
    - GenerateHyloFileTests
    - StandardLibrary
    - IR
    - TestUtils
    - Utils
    custom_documentation_parameters: [
    --include-extended-types, --enable-inherited-docs,
    --source-service, github,
    --source-service-base-url, https://github.com/hylo-lang/hylo/blob/main,
    --checkout-path, .
    ]
