import FrontEnd

extension Module {

  // TODO: remove this
  static func canLowerProjections(_ f: SourceFile) -> Bool {
    let s = f.url.fileSystemPath
    return s.contains("EndToEndTests/TestCases/Projection") && !s.contains("/legacy-")
  }

  /// Returns the type of a continuation generated by the projection.
  static func projectionContinuationType() -> AnyType {
    let addressType = AnyType(BuiltinType.ptr)
    let t = AnyType(
      ArrowType(
        receiverEffect: .let,
        environment: .void,
        inputs: [
          CallableTypeParameter(label: nil, type: ^ParameterType(.`let`, addressType))
        ],
        output: .void))
    return ^TupleType(labelsAndTypes: [("resumeFunction", t), ("frame", addressType)])
  }

  /// Returns the type of a continuation that is able to call a caller plateau, projecting a value of type `p`.
  static func plateauContinuationType(projectedType p: AnyType) -> AnyType {
    let addressType = AnyType(BuiltinType.ptr)
    let t = AnyType(
      ArrowType(
        receiverEffect: .let,
        environment: .void,
        inputs: [
          CallableTypeParameter(label: nil, type: ^ParameterType(.`inout`, p)),
          CallableTypeParameter(label: nil, type: ^ParameterType(.`let`, addressType)),
          CallableTypeParameter(
            label: nil, type: ^ParameterType(.`let`, projectionContinuationType())),
        ],
        output: .void))
    return ^TupleType(labelsAndTypes: [("resumeFunction", t), ("frame", addressType)])
  }

  /// Returns the IR function representing the ramp of projection `f`.
  ///
  /// Signature:
  ///
  ///     fun Projection.ramp(<parameters>, _ c: let PlateauContinuation) -> {}
  ///
  /// Generated function parameters:
  ///   - `<parameters>`: the original parameters of the projection
  ///   - `c`: the continuation used to resume the flow in the plateau,
  ///     containing the function to call and the caller frame pointer.
  mutating func demandProjectionRamp(for f: Function.ID) -> Function.ID {
    let result = Function.ID(projectionRamp: f)
    if functions[result] != nil {
      return result
    }

    let source = self[f]
    var inputs = source.inputs
    let c = Self.plateauContinuationType(projectedType: source.output)
    inputs.append(Parameter(decl: nil, type: ParameterType(.`let`, c)))

    let entity = Function(
      isSubscript: false,
      site: source.site,
      linkage: source.linkage,
      genericParameters: source.genericParameters,
      inputs: inputs,
      output: .void,
      blocks: [])
    addFunction(entity, for: result)
    return result
  }

  /// Returns the IR function representing the slide of projection `f`.
  ///
  /// Signature:
  ///
  ///     fun Projection.slide(_ frame: let Builtin.ptr) -> {}
  ///
  /// Generated function parameters:
  ///   - `frame`: the projection frame pointer.
  mutating func demandProjectionSlide(for f: Function.ID) -> Function.ID {
    let result = Function.ID(projectionSlide: f)
    if self.functions[result] != nil {
      return result
    }

    let source = self[f]
    let inputs = [Parameter(decl: nil, type: ParameterType(.`let`, AnyType(BuiltinType.ptr)))]

    let entity = Function(
      isSubscript: false,
      site: source.site,
      linkage: .module,
      genericParameters: source.genericParameters,
      inputs: inputs,
      output: .void,
      blocks: [])
    addFunction(entity, for: result)
    return result
  }

  /// Returns the IR function representing a plateau region in caller `f` corresponding to the
  /// projected value type `t`.
  ///
  /// Signature:
  ///
  ///       fun Caller.plateauN(_ p: inout <yield-type>, _ frame: let Builtin.ptr, _ c: let ProjectionContinuation) -> {}
  ///
  /// Generated function parameters:
  ///   - `p`: the projected value.
  ///   - `frame`: the address of the caller frame.
  ///   - `c`: the continuation used to resume to the projection's slide,
  ///     containing the function to call and the projection frame pointer.
  mutating func demandPlateau(
    for f: Function.ID, region index: Int, projectedType t: AnyType,
  ) -> Function.ID {
    let result = Function.ID(projectionCallerPlateau: f, region: index)
    if self.functions[result] != nil {
      return result
    }

    let source = self[f]
    let inputs: [Parameter] = [
      Parameter(decl: nil, type: ParameterType(.`inout`, t)),
      Parameter(decl: nil, type: ParameterType(.`let`, AnyType(BuiltinType.ptr))),
      Parameter(decl: nil, type: ParameterType(.`let`, Self.projectionContinuationType())),
    ]

    let entity = Function(
      isSubscript: false,
      site: source.site,
      linkage: .module,
      genericParameters: source.genericParameters,
      inputs: inputs,
      output: .void,
      blocks: [])
    addFunction(entity, for: result)
    return result
  }

}
