name: Check Markdown links

on: [pull_request, push]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        show-progress: false
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
